### ISSUE TITLE
SFTP fails and returns BufferException during file upload

### ISSUE THREAD

**Issue by GabriRuflex** [apache/mina-sshd#275]
### Version

2.9.2

### Bug description

On specific devices I got BufferException exception when I open new SFTP session in order to upload a local file to the remote device.

This is the code I use:

```
...
byte[] localfileBytes = new FileInputStream(localfilepath).readAllBytes();
try (SftpClient sftp = DefaultSftpClientFactory.INSTANCE.createSftpClient(session)) {
    try (SftpClient.CloseableHandle handle = sftp.open(remotefilepath,
                           EnumSet.of(SftpClient.OpenMode.Write, SftpClient.OpenMode.Create))) {
        sftp.write(handle, 0, localfileBytes, 0, localfileBytes.length);
    } catch (IOException e) {}
} catch (IOException e) {}
...
```

### Actual behavior

The file is not uploaded to the remote device. I tried with both relative and absolute paths.

### Expected behavior

The file must be uploaded to the remote device.

### Relevant log output

```Shell
org.apache.sshd.common.util.buffer.BufferException: Underflow: requested=4, available=0
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.ensureAvailable(Buffer.java:635)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getUInt(Buffer.java:281)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getInt(Buffer.java:277)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.ByteArrayBuffer.getString(ByteArrayBuffer.java:240)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getString(Buffer.java:309)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandleResponse(AbstractSftpClient.java:248)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandle(AbstractSftpClient.java:232)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.open(AbstractSftpClient.java:573)
        at deployment.test.ear//com.test.UploadFile.upload(UploadFile.java:106)
```

### Other information

The local device run OpenSSH 8.0p1.

**Comment by tomaswolf** [comment]
What does the _remote_ device run?

Three points:

1. The exception occurs after having received an error reply from the server in response to the `sftp.open()` call. So even if this particular exception is fixed, your problem will not be solved.
2. The `BufferException: Underflow: requested=4, available=0` [at that point](https://github.com/apache/mina-sshd/blob/45fd3a4a84c453a5e053cce624f63465844deb07/sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java#L248) indicates that the server sent no error message or language tag in the error status reply. I can't find any information that would say these were optional... but Apache MINA sshd could perhaps be lenient and consider them so.
3. The failing code has been touched last 8 years ago, so the problem is certainly not new in 2.9.2. I wonder why this problem never was reported before?

**Comment by GabriRuflex** [comment]
Hi Tomas and thanks for your support!

> What does the _remote_ device run?

SSH 2.0, unfortunately no more details :( 

> Three points:
> 
>     1. The exception occurs after having received an error reply from the server in response to the `sftp.open()` call. So even if this particular exception is fixed, your problem will not be solved.

I tried also to mount the remote filesystem but it's still not working (only in that specific device)
```
...
SftpFileSystemProvider provider = new SftpFileSystemProvider(client);
try (FileSystem fs = provider.newFileSystem(session)) {
    Path remotePath = fs.getPath(remotefilepath);
    try {
        Files.copy(localfileStream, remotePath, StandardCopyOption.REPLACE_EXISTING);
    } catch (IOException e) {}
}
...
```

```
org.apache.sshd.common.util.buffer.BufferException: Underflow: requested=4, available=0
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.ensureAvailable(Buffer.java:635)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getUInt(Buffer.java:281)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getInt(Buffer.java:277)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.ByteArrayBuffer.getString(ByteArrayBuffer.java:240)
        at deployment.test.ear//org.apache.sshd.common.util.buffer.Buffer.getString(Buffer.java:309)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkAttributesResponse(AbstractSftpClient.java:298)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkAttributes(AbstractSftpClient.java:283)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.stat(AbstractSftpClient.java:997)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystem$Wrapper.stat(SftpFileSystem.java:412)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.resolveRemoteFileAttributes(SftpFileSystemProvider.java:981)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.lambda$readRemoteAttributes$0(SftpFileSystemProvider.java:969)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.SftpPathImpl.withAttributeCache(SftpPathImpl.java:120)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.SftpPathImpl.withAttributeCache(SftpPathImpl.java:140)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.readRemoteAttributes(SftpFileSystemProvider.java:969)
        at deployment.test.ear//org.apache.sshd.sftp.client.impl.AbstractSftpFileAttributeView.readRemoteAttributes(AbstractSftpFileAttributeView.java:71)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpPosixFileAttributeView.readAttributes(SftpPosixFileAttributeView.java:52)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpPosixFileAttributeView.readAttributes(SftpPosixFileAttributeView.java:40)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.checkAccess(SftpFileSystemProvider.java:826)
        at deployment.test.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.delete(SftpFileSystemProvider.java:581)
        at java.base/java.nio.file.spi.FileSystemProvider.deleteIfExists(FileSystemProvider.java:787)
        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
        at java.base/java.nio.file.Files.copy(Files.java:3055)
        at deployment.test.ear//com.test.UploadFile.upload(UploadFile.java:109)
```

>     2. The `BufferException: Underflow: requested=4, available=0` [at that point](https://github.com/apache/mina-sshd/blob/45fd3a4a84c453a5e053cce624f63465844deb07/sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java#L248) indicates that the server sent no error message or language tag in the error status reply. I can't find any information that would say these were optional... but Apache MINA sshd could perhaps be lenient and consider them so.

I can login to that device via CLI using `ssh` or `sftp` tools. Also other java libraries can do that.

>     3. The failing code has been touched last 8 years ago, so the problem is certainly not new in 2.9.2. I wonder why this problem never was reported before? Probably the remote device runs a very old version of SFTP. [Prior to SFTP version 3](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-09#section-12.4), the SSH_FXP_STATUS reply indeed didn't have the error message and language tag fields.

I'm trying to migrate from another java library (which is working properly) to Apache MINA sshd so I don't know if this issue is new or it a regression related to the latest version

On the old library I just added a try catch to ignore the SSH_FXP_STATUS error and go ahead with the execution.

The current SFTP version is 3
```
sftp> version
SFTP protocol version 3
```

**Comment by tomaswolf** [comment]
Could you please run your client code with debug logging on and post or attach the log here?

**Comment by GabriRuflex** [comment]
> Could you please run your client code with debug logging on and post or attach the log here?

Put file:
```
sftp> put test.dat 
debug3: Looking up test.dat
Uploading test.dat to /test.dat
debug3: Sent message SSH2_FXP_OPEN I:2 P:/test.dat
test.dat                                                                                                                                                                    100%    0     0.0KB/s   00:00    
debug3: Sent message SSH2_FXP_CLOSE I:3
debug3: SSH2_FXP_STATUS 0
sftp>
```

LS and remove file:
```
sftp> rm tesdebug3: Sending SSH2_FXP_READDIR I:26
debug3: Received reply T:104 I:26
debug3: Received 23 SSH2_FXP_NAME responses
debug3: Sending SSH2_FXP_READDIR I:27
debug3: Received reply T:101 I:27
debug3: Received SSH2_FXP_STATUS 1
debug3: Sent message SSH2_FXP_CLOSE I:28
debug3: SSH2_FXP_STATUS 0
debug3: Sent message fd 3 T:7 I:29
debug3: Received stat reply T:105 I:29
sftp> rm test.dat 
debug3: Sent message fd 3 T:7 I:30
debug3: Received stat reply T:105 I:30
Removing /test.dat
debug2: Sending SSH2_FXP_REMOVE "/test.dat"
debug3: Sent message fd 3 T:13 I:31
debug3: SSH2_FXP_STATUS 0
sftp>
```

If I try to remove the file using MINA sshd library, the file is removed but a BufferException is returned:
```
org.apache.sshd.common.util.buffer.BufferException: Underflow: requested=4, available=0
        at deployment.hpsa.ear//org.apache.sshd.common.util.buffer.Buffer.ensureAvailable(Buffer.java:635)
        at deployment.hpsa.ear//org.apache.sshd.common.util.buffer.Buffer.getUInt(Buffer.java:281)
        at deployment.hpsa.ear//org.apache.sshd.common.util.buffer.Buffer.getInt(Buffer.java:277)
        at deployment.hpsa.ear//org.apache.sshd.common.util.buffer.ByteArrayBuffer.getString(ByteArrayBuffer.java:240)
        at deployment.hpsa.ear//org.apache.sshd.common.util.buffer.Buffer.getString(Buffer.java:309)
        at deployment.hpsa.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkResponseStatus(AbstractSftpClient.java:184)
        at deployment.hpsa.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkCommandStatus(AbstractSftpClient.java:164)
        at deployment.hpsa.ear//org.apache.sshd.sftp.client.impl.AbstractSftpClient.remove(AbstractSftpClient.java:608)
        at deployment.hpsa.ear//org.apache.sshd.sftp.client.fs.SftpFileSystem$Wrapper.remove(SftpFileSystem.java:330)
        at deployment.hpsa.ear//org.apache.sshd.sftp.client.fs.SftpFileSystemProvider.delete(SftpFileSystemProvider.java:593)
        at java.base/java.nio.file.spi.FileSystemProvider.deleteIfExists(FileSystemProvider.java:787)
        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
```

**Comment by tomaswolf** [comment]
Sorry for not having been clear enough: I'm interested in the debug log of your _Java client that is using Apache MINA SSHD and that is getting the exception_. And please show the full log from the initial connection to the exception.

**Comment by tomaswolf** [comment]
Thanks. So this is some device using Huawei VRP. (The server identifies as SSH-2.0-HUAWEI-1.5.) Indeed the negotiated SFTP version is SFTP v3.

I'll fix this `BufferException: Underflow` and improve SFTP logging, but as I wrote above, I don't think this will resolve the problem with this device. But maybe with better logging we can then see better what might be going on.

**Comment by tomaswolf** [comment]
>Probably the remote device runs a very old version of SFTP. [Prior to SFTP version 3](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-09#section-12.4), the SSH_FXP_STATUS reply indeed didn't have the error message and language tag fields.

Actually, it's a bit worse: the [very first of the SFTP v3 drafts](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-00#section-7) also did not have these two fields yet. They appeared only in the [second SFTPv3 draft](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-01#section-6).

Therefore there may indeed be old servers that implement only that very early specification, and rightfully claim to implement SFTPv3 but not send these fields. In order to support such old SFTPv3 servers, an SFTP client _must_ treat the error message and language tag fields in SSH_FXP_STATUS as optional.

**Comment by tomaswolf** [comment]
@GabriRuflex : a fix for this problem has been merged. If there is still a problem with SFTP uploads to that device using the current master branch of Apache MINA SSHD, feel free to open a new bug report. (I suspect there might be, since the server should respond to an open() call with an SSH_FXP_STATUS reply only if it encountered an error. If the open() succeeds, it should send back an SSH_FXP_HANDLE response.)

**Comment by GabriRuflex** [comment]
> @GabriRuflex : a fix for this problem has been merged. If there is still a problem with SFTP uploads to that device using the current master branch of Apache MINA SSHD, feel free to open a new bug report. (I suspect there might be, since the server should respond to an open() call with an SSH_FXP_STATUS reply only if it encountered an error. If the open() succeeds, it should send back an SSH_FXP_HANDLE response.)

Thanks Tomas.

I'll test it on monday and I'll inform you about the results :smile:

**Comment by GabriRuflex** [comment]
@tomaswolf

If I use the SftpFileSystemProvider there are no issue anymore and the file upload works properly, thanks!

> ```
> SftpFileSystemProvider provider = new SftpFileSystemProvider(client);
> try (FileSystem fs = provider.newFileSystem(session)) {
>     Path remotePath = fs.getPath(remotefilepath);
>     try {
>         Files.copy(localfileStream, remotePath, StandardCopyOption.REPLACE_EXISTING);
>     } catch (IOException e) {}
> }
> ```

Log:

```
[org.apache.sshd.client.session.ClientSessionImpl] doHandleMessage(ClientSessionImpl[admin@/10.0.0.1:22]) process #10 SSH_MSG_CHANNEL_DATA
[org.apache.sshd.common.channel.LocalWindow] Consume LocalWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 13 down to 2097103
[org.apache.sshd.sftp.client.impl.DefaultSftpClient$SftpChannelSubsystem] handleData(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) SSH_MSG_CHANNEL_DATA len=13
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] validateIncomingResponse(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]): received SSH_FXP_STATUS(SSH_FX_NO_SUCH_FILE) for command SSH_FXP_STAT (id=102)
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] throwStatusException(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp])[id=102] cmd=SSH_FXP_STAT status=SSH_FXP_STATUS[SSH_FX_NO_SUCH_FILE ,language=null ,message=null]
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] open(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]): send SSH_FXP_OPEN /test.dat
[org.apache.sshd.common.channel.RemoteWindow] Consume RemoteWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 63 down to 130931
[org.apache.sshd.client.session.ClientSessionImpl] encode(ClientSessionImpl[admin@/10.0.0.1:22]) packet #11 sending command=94[SSH_MSG_CHANNEL_DATA] len=72
[org.apache.sshd.common.io.nio2.Nio2Session] writeBuffer(Nio2Session[local=/127.0.0.1:44642, remote=/10.0.0.1:22]) writing 128 bytes
[org.apache.sshd.client.session.ClientSessionImpl] doHandleMessage(ClientSessionImpl[admin@/10.0.0.1:22]) process #11 SSH_MSG_CHANNEL_DATA
[org.apache.sshd.common.channel.LocalWindow] Consume LocalWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 17 down to 2097086
[org.apache.sshd.sftp.client.impl.DefaultSftpClient$SftpChannelSubsystem] handleData(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) SSH_MSG_CHANNEL_DATA len=17
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] validateIncomingResponse(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]): received SSH_FXP_HANDLE for command SSH_FXP_OPEN (id=103)
```



If I use a simple SftpClient with `open` and `handle` functions I still have issue and I can't upload the file:

> ```
>                 try (SftpClient sftp = DefaultSftpClientFactory.INSTANCE.createSftpClient(session)) {
>                     try (SftpClient.CloseableHandle handle = sftp.open(remotefilepath, EnumSet.of(SftpClient.OpenMode.Write, SftpClient.OpenMode.Create))) {
>                         sftp.write(handle, 0, localfileBytes, 0, localfileBytes.length);
>                     } catch (IOException ignored) { }
>                 } catch (IOException ignored) { }
>             } catch (IOException ignored) { }
>         } catch (IOException ignored) { }
>     }
> ```

Log:

```
[org.apache.sshd.client.session.ClientSessionImpl] doHandleMessage(ClientSessionImpl[admin@/10.0.0.1:22]) process #8 SSH_MSG_CHANNEL_DATA
[org.apache.sshd.common.channel.LocalWindow] Consume LocalWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 9 down to 2097143
[org.apache.sshd.sftp.client.impl.DefaultSftpClient$SftpChannelSubsystem] handleData(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) SSH_MSG_CHANNEL_DATA len=9
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] negotiateVersion(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) current=3 [3] -> 3
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] open(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]): send SSH_FXP_OPEN /test.dat
[org.apache.sshd.common.channel.RemoteWindow] Consume RemoteWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 37 down to 131026
[org.apache.sshd.client.session.ClientSessionImpl] encode(ClientSessionImpl[admin@/10.0.0.1:22]) packet #9 sending command=94[SSH_MSG_CHANNEL_DATA] len=46
[org.apache.sshd.common.io.nio2.Nio2Session] writeBuffer(Nio2Session[local=/127.0.0.1:60194, remote=/10.0.0.1:22]) writing 112 bytes
[org.apache.sshd.client.session.ClientSessionImpl] doHandleMessage(ClientSessionImpl[admin@/10.0.0.1:22]) process #9 SSH_MSG_CHANNEL_DATA
[org.apache.sshd.common.channel.LocalWindow] Consume LocalWindow[client](SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) by 13 down to 2097130
[org.apache.sshd.sftp.client.impl.DefaultSftpClient$SftpChannelSubsystem] handleData(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]) SSH_MSG_CHANNEL_DATA len=13
[org.apache.sshd.sftp.client.impl.DefaultSftpClient] validateIncomingResponse(SftpChannelSubsystem[id=0, recipient=1]-ClientSessionImpl[admin@/10.0.0.1:22][sftp]): received SSH_FXP_STATUS(SSH_FX_FAILURE) for command SSH_FXP_OPEN (id=101)
```

**Comment by tomaswolf** [comment]
Looks like we should also write the file open modes to the log.

Using the file system

- the file will be deleted first if it existed (it didn't, as the stat response shows), and
- the open() call will include the `Exclusive` flag.

I don't know why the server seems to have a problem with the direct open() call. I don't really see how I could help here further. AFAIK, the actual open() call is in both cases the very same piece of code in Apache MINA sshd. So any difference in server behavior must be caused by different request parameters (different flags), or a different device state (such as the file already existing).
