### ISSUE TITLE
ssh links init fail, throw Exception.Do anyone know what cause it or how to fix it 

### ISSUE THREAD

**Issue by bbhark** [apache/mina-sshd#331]
java.lang.IllegalStateException: Channel id=0 not registered because session is being closed: ChannelShell[id=0, recipient=-1]-ClientSessionImpl[root@null]
	at org.apache.sshd.common.channel.AbstractChannel.handleChannelRegistrationResult(AbstractChannel.java:440) ~[sshd-core-2.9.2.jar:2.9.2]
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.registerChannel(AbstractConnectionService.java:423) ~[sshd-core-2.9.2.jar:2.9.2]
	at org.apache.sshd.client.session.AbstractClientSession.createShellChannel(AbstractClientSession.java:500) ~[sshd-core-2.9.2.jar:2.9.2]
	at org.apache.sshd.client.session.ClientSession.createShellChannel(ClientSession.java:159) ~[sshd-core-2.9.2.jar:2.9.2]

**Comment by alfabravoteam** [comment]
Finding this same behavior since I updated to latest plugin version `2.14.0-143.v2b_362fc39576` for Jenkins 2.494

```
INFO: Creating ~/.hudson-run-init
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
Also:   java.lang.Throwable: launched here
		at hudson.slaves.SlaveComputer._connect(SlaveComputer.java:286)
		at hudson.model.Computer.connect(Computer.java:437)
		at PluginClassLoader for ec2//hudson.plugins.ec2.EC2RetentionStrategy.start(EC2RetentionStrategy.java:304)
		at PluginClassLoader for ec2//hudson.plugins.ec2.EC2RetentionStrategy.start(EC2RetentionStrategy.java:49)
		at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:192)
		at hudson.model.AbstractCIBase.updateNewComputer(AbstractCIBase.java:221)
		at jenkins.model.Jenkins.updateNewComputer(Jenkins.java:1589)

...


java.lang.IllegalStateException: Channel id=4 not registered because session is being closed: ChannelExec[id=4, recipient=-1]-ClientSessionImpl[ec2-user@/PRIVATE_IP:22]
	at PluginClassLoader for mina-sshd-api-core//org.apache.sshd.common.channel.AbstractChannel.handleChannelRegistrationResult(AbstractChannel.java:471)
	at PluginClassLoader for mina-sshd-api-core//org.apache.sshd.common.session.helpers.AbstractConnectionService.registerChannel(AbstractConnectionService.java:424)
	at PluginClassLoader for mina-sshd-api-core//org.apache.sshd.client.session.AbstractClientSession.createExecChannel(AbstractClientSession.java:390)
	at PluginClassLoader for ec2//hudson.plugins.ec2.ssh.EC2UnixLauncher.launchScript(EC2UnixLauncher.java:287)
	at PluginClassLoader for ec2//hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:55)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
