### ISSUE TITLE
Azure JCA Provider Not Being Recognized -- 

### ISSUE THREAD

**Issue by yuruhimesama** [apache/mina-sshd#412]
### Version

2.10

### Bug description

I am trying to integrate the [Azure Keyvault JCA library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/keyvault/azure-security-keyvault-jca) when creating client connections. Idea is that I can keep a bespoke keypair for each remote host and call upon the correct keypair to establish the connection for the desired host at runtime. The trouble is that somewhere deep in the java security configuration is a configuration mismatch: when calling `ClientSession.auth()`, Java is unable to figure out how to use the underlying `PrivateKey`, which is strange given that the Keyvault implementation is native JCE -- standard `KeyStore`, `PublicKey`, `PrivateKey`. I am not doing anything bespoke for the security provider beyond `Security.addProvider().`

### Code Snippets
```java
        KeyVaultJcaProvider provider = new KeyVaultJcaProvider();
        Security.addProvider(provider);
//...
        X509Certificate cert = (X509Certificate) ks.getCertificate("sshcert");
        PublicKey pk = cert.getPublicKey();
        
        PrivateKey privkey = (PrivateKey) ks.getKey("sshcert", null);

        KeyPair clientIdentityKeypair = new KeyPair(pk, privkey);

//...
        ClientSession session = client.connect("ssh://user@remotehost:22").verify(Duration.ofMinutes(1), CancelOption.CANCEL_ON_TIMEOUT).getClientSession();
        session.addPublicKeyIdentity(clientIdentityKeypair);

        session.auth().verify(Duration.ofSeconds(15),CancelOption.CANCEL_ON_TIMEOUT);

```

### Stack Trace

```java
Exception in thread "main" org.apache.sshd.common.SshException: [ssh-connection]: Failed (InvalidKeyException) to execute: No installed provider supports this key: com.azure.security.keyvault.jca.implementation.KeyVaultPrivateKey
        at org.apache.sshd.common.future.AbstractSshFuture.lambda$verifyResult$2(AbstractSshFuture.java:146)
        at org.apache.sshd.common.future.AbstractSshFuture.formatExceptionMessage(AbstractSshFuture.java:206)
        at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:145)
        at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:56)
        at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:35)
        at org.apache.sshd.common.future.VerifiableFuture.verify(VerifiableFuture.java:74)
        at com.boeing.fleetlink.Mina.main(Mina.java:97)
Caused by: java.security.InvalidKeyException: No installed provider supports this key: com.azure.security.keyvault.jca.implementation.KeyVaultPrivateKey
        at java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1284)
        at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1354)
        at java.base/java.security.Signature.initSign(Signature.java:636)
        at org.apache.sshd.common.signature.AbstractSignature.initSigner(AbstractSignature.java:104)
        at org.apache.sshd.client.auth.pubkey.KeyPairIdentity.sign(KeyPairIdentity.java:81)
        at org.apache.sshd.client.auth.pubkey.UserAuthPublicKey.appendSignature(UserAuthPublicKey.java:446)
        at org.apache.sshd.client.auth.pubkey.UserAuthPublicKey.processAuthDataRequest(UserAuthPublicKey.java:413)
        at org.apache.sshd.client.auth.AbstractUserAuth.process(AbstractUserAuth.java:88)
        at org.apache.sshd.client.session.ClientUserAuthService.processUserAuth(ClientUserAuthService.java:345)
        at org.apache.sshd.client.session.ClientUserAuthService.process(ClientUserAuthService.java:267)
        at org.apache.sshd.common.session.helpers.CurrentService.process(CurrentService.java:109)
        at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:592)
        at org.apache.sshd.common.session.helpers.AbstractSession.lambda$handleMessage$0(AbstractSession.java:523)
        at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:68)
        at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:522)
        at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1649)
        at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:483)
        at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:64)
        at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:407)
        at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:380)
        at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:375)
        at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

A successful connection.

**Comment by tomaswolf** [comment]
I cannot really help with this since I don't use this Azure Key Vault. However, I notice that they register their [Signature service without parameters](https://github.com/Azure/azure-sdk-for-java/blob/004e5c76d1d852a055e09fc35bbbf1b06b3035d6/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultJcaProvider.java#L111). Since [no `SupportedKeyClasses`](https://github.com/openjdk/jdk/blob/b2728cb139c9d8d378820f848afe8e83fe5be471/src/java.base/share/classes/java/security/Provider.java#L2097) are defined, [`Signature$Delegate.chooseProvider()`](https://github.com/openjdk/jdk/blob/b2728cb139c9d8d378820f848afe8e83fe5be471/src/java.base/share/classes/java/security/Signature.java#L1267) will not find the provider for this key type.

Presumably it could work if the Signature was obtained via `Signature.getInstance(algorithm, provider)`, passing in the provider you created. But Apache MINA sshd has no support in its built-in signatures for passing in a specific provider, so you'd have to implement something yourself.

But apart from that, I don't think Apache MINA sshd has any built-in RSA signature that would map to the ["RSASSA-PSS"](https://github.com/Azure/azure-sdk-for-java/blob/004e5c76d1d852a055e09fc35bbbf1b06b3035d6/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/implementation/signature/KeyVaultKeyLessRsaSignature.java#L61C17-L61C27) algorithm name. I'm not aware of that algorithm being used in SSH at all.

Perhaps it might work with EC keys (once you've solved getting a signature object for a specific provider).

**Comment by yuruhimesama** [comment]
Curious, thank you for the insight into why the stack trace is returning what it does.

As for the algorithm, everything we do defaults to RSA but I can generate EC keypairs and give it another go. That doesn't concern me nearly as much as MINA's own ability to be made aware of the external provider. Do you have any suggestions? I did some experimentation with `AbstractSecurityProviderRegistrar` but I'm just not experienced enough with JCA to work through it (yet).

**Comment by yuruhimesama** [comment]
Update -- altering to an EC256 key solved the whole problem. Thank you for alerting me to it. I'm glad I do not have to attempt any interventions with the `Registrar` mechanics.
