### ISSUE TITLE
 SSH Client Disconnects on Receiving Keepalive Requests

### ISSUE THREAD

**Issue by coderZoe** [apache/mina-sshd#482]
### Version

group: 'org.apache.sshd',name: 'sshd-core',version: '2.12.0'

### Bug description

After my SSH client receives the message `o.a.sshd.client.channel.ChannelShell - handleUnknownChannelRequest(ChannelShell[id=0, recipient=0]-ClientSessionImpl[admin@/10.252.146.106:61122]) Unknown channel request: keepalive@openssh.com[want-reply=true]`, it immediately disconnects from the server (it is possible that the server is the one terminating the connection).

However, I have already set `KeepAliveHandler.INSTANCE` in the `GlobalRequestHandlers` when creating the client. Debugging the code shows that it does not enter the `KeepAliveHandler#process()` method, which seems to indicate that the setting of `GlobalRequestHandlers` has no effect.

### Actual behavior

After my SSH client receives the message `o.a.sshd.client.channel.ChannelShell - handleUnknownChannelRequest(ChannelShell[id=0, recipient=0]-ClientSessionImpl[admin@/10.252.146.106:61122]) Unknown channel request: keepalive@openssh.com[want-reply=true]`, it immediately disconnects from the server (it is possible that the server is the one terminating the connection).

### Expected behavior

Why is this happening? Is it because the server sent a keepalive packet and I did not respond, causing the server to terminate the connection? I do not wish to disconnect and reconnect every so often; I want to maintain a long connection. If it is due to not responding to the server's keepalive packets, what should I do to keep the connection alive at all times?

### Relevant log output

```Shell
here is the log:

[WARN ] 10:16:53.178 [sshd-SshClient[72dd8b0]-nio2-thread-1] [          ] o.a.sshd.client.channel.ChannelShell - handleUnknownChannelRequest(ChannelShell[id=0, recipient=0]-ClientSessionImpl[admin@/10.252.146.106:61122]) Unknown channel request: keepalive@openssh.com[want-reply=true]


```log
org.apache.sshd.common.SshException: IoReadFutureImpl[ChannelAsyncInputStream[ChannelShell[id=0, recipient=0]-ClientSessionImpl[admin@/10.252.146.106:61122]]]: Failed (EOFException) to execute: Closed
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$verifyResult$2(AbstractSshFuture.java:146)
	at org.apache.sshd.common.future.AbstractSshFuture.formatExceptionMessage(AbstractSshFuture.java:206)
	at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:145)
	at org.apache.sshd.common.channel.ChannelAsyncInputStream$IoReadFutureImpl.verify(ChannelAsyncInputStream.java:173)
	at org.apache.sshd.common.channel.ChannelAsyncInputStream$IoReadFutureImpl.verify(ChannelAsyncInputStream.java:156)
	at org.apache.sshd.common.future.VerifiableFuture.verify(VerifiableFuture.java:74)
	at com.uca.network.v2.communication.core.sender.session.BaseSshSessionSender$ChannelResponseListener.operationComplete(BaseSshSessionSender.java:290)
	at com.uca.network.v2.communication.core.sender.session.BaseSshSessionSender$ChannelResponseListener.operationComplete(BaseSshSessionSender.java:268)
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$notifyListener$3(AbstractSshFuture.java:178)
	at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:64)
	at org.apache.sshd.common.future.AbstractSshFuture.notifyListener(AbstractSshFuture.java:177)
	at org.apache.sshd.common.future.DefaultSshFuture.notifyListeners(DefaultSshFuture.java:257)
	at org.apache.sshd.common.future.DefaultSshFuture.setValue(DefaultSshFuture.java:160)
	at org.apache.sshd.common.channel.ChannelAsyncInputStream.preClose(ChannelAsyncInputStream.java:98)
	at org.apache.sshd.common.util.closeable.AbstractCloseable.close(AbstractCloseable.java:109)
	at org.apache.sshd.common.util.closeable.ParallelCloseable.doClose(ParallelCloseable.java:65)
	at org.apache.sshd.common.util.closeable.SimpleCloseable.close(SimpleCloseable.java:63)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:56)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:45)
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$notifyListener$3(AbstractSshFuture.java:178)
	at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:64)
	at org.apache.sshd.common.future.AbstractSshFuture.notifyListener(AbstractSshFuture.java:177)
	at org.apache.sshd.common.future.DefaultSshFuture.addListener(DefaultSshFuture.java:214)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:57)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:45)
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$notifyListener$3(AbstractSshFuture.java:178)
	at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:64)
	at org.apache.sshd.common.future.AbstractSshFuture.notifyListener(AbstractSshFuture.java:177)
	at org.apache.sshd.common.future.DefaultSshFuture.addListener(DefaultSshFuture.java:214)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:57)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:45)
	at org.apache.sshd.common.util.closeable.SequentialCloseable.doClose(SequentialCloseable.java:69)
	at org.apache.sshd.common.util.closeable.SimpleCloseable.close(SimpleCloseable.java:63)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:56)
	at org.apache.sshd.common.util.closeable.SequentialCloseable$1.operationComplete(SequentialCloseable.java:45)
	at org.apache.sshd.common.util.closeable.SequentialCloseable.doClose(SequentialCloseable.java:69)
	at org.apache.sshd.common.util.closeable.SimpleCloseable.close(SimpleCloseable.java:63)
	at org.apache.sshd.common.util.closeable.AbstractInnerCloseable.doCloseGracefully(AbstractInnerCloseable.java:41)
	at org.apache.sshd.common.util.closeable.AbstractCloseable.close(AbstractCloseable.java:110)
	at org.apache.sshd.common.channel.AbstractChannel.handleClose(AbstractChannel.java:578)
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.channelClose(AbstractConnectionService.java:644)
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.process(AbstractConnectionService.java:483)
	at org.apache.sshd.common.session.helpers.CurrentService.process(CurrentService.java:109)
	at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:624)
	at org.apache.sshd.common.session.helpers.AbstractSession.lambda$handleMessage$0(AbstractSession.java:545)
	at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:68)
	at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:544)
	at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1688)
	at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:505)
	at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:64)
	at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:409)
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:382)
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:377)
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.EOFException: Closed
	... 49 common frames omitted
```

Here is the code I used to set up the client:
```java
this.client = SshClient.setUpDefaultClient();
this.client.start();
this.client.setGlobalRequestHandlers(Arrays.asList(KeepAliveHandler.INSTANCE, NoMoreSessionsHandler.INSTANCE));

ConnectFuture connectFuture = client.connect(metaData.getUserName(), metaData.getIp(), metaData.getPort())
        .verify(metaData.getConnectTimeout());
if (connectFuture.isConnected()) {
    this.session = connectFuture.getSession();
} else {
    throw new ConnectException(connectFuture.getException().getMessage());
}

this.session.addPasswordIdentity(metaData.getPassword());
AuthFuture authFuture = this.session.auth().verify(metaData.getAuthTimeout());
if (authFuture.isSuccess()) {
    this.status = SenderStatus.CONNECTING;
} else {
    throw new AuthException("Auth Fail:" + authFuture.getException().getMessage());
}
this.channel = createChannel();

```

```java
public ClientChannel createChannel() throws Exception {
    ClientChannel channel = this.session.createChannel(ClientChannel.CHANNEL_SHELL);
    channel.setStreaming(ClientChannel.Streaming.Async);
    channel.open().verify();
    channel.getAsyncOut().read(new ByteArrayBuffer(BUFFER_PIPE_SIZE)).addListener(new ChannelResponseListener(this));
    return channel;
}

```
```


### Other information

_No response_

**Comment by tomaswolf** [comment]
Setting a "global request" handler for keep-alives has only an effect on global requests. It has no effect on channel requests. OpenSSH prefers to send keep-alive messages a channel requests if a channel is open, and then expects a failure reply.

Apache MINA SSHD actually behaves like OpenSSH expects; the only problem is that it logs this warning. That's issue [SSHD-1237](https://issues.apache.org/jira/browse/SSHD-1237).

I don't think your problem is related to this warning. But I don't know what might cause your problem; it looks like your code is reading from a `ChannelAsyncInputStream` when that stream is being closed. Why it is being closed I cannot tell.

**Comment by coderZoe** [comment]
> Setting a "global request" handler for keep-alives has only an effect on global requests. It has no effect on channel requests. OpenSSH prefers to send keep-alive messages a channel requests if a channel is open, and then expects a failure reply.
> 
> Apache MINA SSHD actually behaves like OpenSSH expects; the only problem is that it logs this warning. That's issue [SSHD-1237](https://issues.apache.org/jira/browse/SSHD-1237).
> 
> I don't think your problem is related to this warning. But I don't know what might cause your problem; it looks like your code is reading from a `ChannelAsyncInputStream` when that stream is being closed. Why it is being closed I cannot tell.

I think I understand why the connection was actively disconnected because the server's sshd_config is configured with ClientAliveInterval 600. Regarding your second issue, to resolve the warning logs like `o.a.sshd.client.channel.ChannelShell - handleUnknownChannelRequest(ChannelShell[id=0, recipient=0]-ClientSessionImpl[admin@/10.252.146.106:61122]) Unknown channel request: keepalive@openssh.com[want-reply=true]`, I looked at the Jira link you provided. This means the KeepAliveHandler.INSTANCE I set in globalRequestHandlers did not affect individual channels. If I want it to work and avoid these warnings, do I need to add a request handler for each channel and implement logic similar to KeepAliveHandler.INSTANCE within them?

**Comment by tomaswolf** [comment]
Basically yes, but see #492. The next version of Apache MINA SSHD will handle these channel requests and no longer log the warning.

As I wrote, I don't think your problem is related to this warning.

**Comment by coderZoe** [comment]
> Basically yes, but see #492. The next version of Apache MINA SSHD will handle these channel requests and no longer log the warning.
> 
> As I wrote, I don't think your problem is related to this warning.

thanks

**Comment by ruanwenjun** [comment]
@coderZoe @tomaswolf Hi, I meet a problem related to the ssh keepalive.
My task failed seems due to the ssh channel closed, I am not sure if this is due to the heartbeat miss.

```
exceptionCaught(ClientSessionImpl[cebwmapp@/10.227.23.69:16022])[state=Opened] IOException: Connection reset by peer
```

My code is look like below
```
SshClient sshClient = SshClient.setUpDefaultClient();
sshClient.start();

ClientSession session = sshClient.connect(
                    sshConnectionParam.getUsername(),
                    sshConnectionParam.getHost(),
                    sshConnectionParam.getPort()).verify(timeout).getSession();
String password = sshConnectionParam.getPassword();
if (StringUtils.isNotEmpty(password)) {
    session.addPasswordIdentity(password);
}
String privateKey = sshConnectionParam.getPrivateKey();
if (StringUtils.isNotEmpty(privateKey)) {
    KeyPairResourceLoader loader = SecurityUtils.getKeyPairResourceParser();
    Collection<KeyPair> keyPairCollection = loader.loadKeyPairs(null, null, null, privateKey);
    for (KeyPair keyPair : keyPairCollection) {
        session.addPublicKeyIdentity(keyPair);
    }
}
if (!session.auth().verify(Duration.ofSeconds(timeout)).isSuccess()) {
    throw new RuntimeException("Session auth failed");
}
session.setSessionHeartbeat(SessionHeartbeatController.HeartbeatType.IGNORE,
        Duration.ofSeconds(PropertyUtils.getInt("session-connection-heartbeat-interval", 5)));
return session;
```

Do I need to add KeepAliveHandler.INSTANCE in globalRequestHandlers to avoid this?
