### ISSUE TITLE
AuthTimeout when connecting to SFTP server

### ISSUE THREAD

**Issue by yaroslavambrozyak** [apache/mina-sshd#484]
### Version

2.9.2

### Bug description

Hi, I recently migrated a project to Spring Boot 3 and faced an issue connecting to a remote SFTP server. I get a timeout during auth, this is what I see in logs
```
Disconnecting(ClientSessionImpl[someuser@somehost/0.0.0.0:22]): SSH2_DISCONNECT_PROTOCOL_ERROR - Detected AuthTimeout after 120823/120000 ms.
```
If I spawn an SFTP docker container on my local then I can connect to my local SFTP, also I can connect to the remote server if I use Spring Boot 2.x version.

Can I run it in verbose or debug mode to see some additional information? 
I really appreciate any help you can provide.

### Actual behavior

I have tried to connect to a remote server using simple code
```
SshClient sshClient = SshClient.setUpDefaultClient();
        
sshClient.start();
ConnectFuture connect = sshClient.connect("username", "host", 22);
ClientSession clientSession = connect.verify().getClientSession();
clientSession.addPasswordIdentity("pass");

AuthFuture authFuture = clientSession.auth().verify();
```
so it hangs on the last line and after some time prints a log I mentioned above
The same code is working if I try to connect to my local SFTP server (it does not throw any timeout exception)

### Expected behavior

Be able to connect to the server

### Relevant log output

```Shell
2024-04-15T17:30:02.807+03:00  INFO 35672 --- [           main] o.a.s.c.i.DefaultIoServiceFactoryFactory : No detected/configured IoServiceFactoryFactory; using Nio2ServiceFactoryFactory
2024-04-15T17:30:02.833+03:00  INFO 35672 --- [           main] c.c.h.DefaultConfigFileHostEntryResolver : resolveEffectiveResolver(<some_host>) no configuration file at C:\Users\User1\.ssh\config

2024-04-15T17:30:03.134+03:00  WARN 35672 --- []-nio2-thread-6] o.a.s.c.k.AcceptAllServerKeyVerifier     : Server at <some_host> presented unverified RSA key: SHA256:vT...n+w
2024-04-15T17:32:03.807+03:00  INFO 35672 --- [-timer-thread-1] o.a.s.client.session.ClientSessionImpl   : Disconnecting(ClientSessionImpl[<some_host>]): SSH2_DISCONNECT_PROTOCOL_ERROR - Detected AuthTimeout after 120823/120000 ms.

org.apache.sshd.common.SshException: Session is being closed
	at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:141)
	at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:56)
	at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:35)
	at org.apache.sshd.common.future.VerifiableFuture.verify(VerifiableFuture.java:43)
	at com.example.sftpdebug.SftpdebugApplication.main(SftpdebugApplication.java:31)
Caused by: org.apache.sshd.common.SshException: Session is being closed
	at org.apache.sshd.client.session.ClientSessionImpl.preClose(ClientSessionImpl.java:169)
	at org.apache.sshd.common.util.closeable.AbstractCloseable.close(AbstractCloseable.java:94)
	at org.apache.sshd.common.session.helpers.SessionHelper.lambda$disconnect$9(SessionHelper.java:1213)
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$notifyListener$3(AbstractSshFuture.java:178)
	at org.apache.sshd.common.util.threads.ThreadUtils.runAsInternal(ThreadUtils.java:68)
	at org.apache.sshd.common.future.AbstractSshFuture.notifyListener(AbstractSshFuture.java:177)
	at org.apache.sshd.common.future.DefaultSshFuture.addListener(DefaultSshFuture.java:214)
	at org.apache.sshd.common.session.helpers.SessionHelper.disconnect(SessionHelper.java:1197)
	at org.apache.sshd.common.session.helpers.SessionHelper.checkForTimeouts(SessionHelper.java:301)
	at org.apache.sshd.common.session.helpers.SessionTimeoutListener.run(SessionTimeoutListener.java:84)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tomaswolf** [comment]
No idea. Try enabling debug logging and see if the log gives any hints.

**Comment by yaroslavambrozyak** [comment]
In the logs, I can see it is trying to use keyboard-interactive auth method
```
tryNext(ClientSessionImpl[u@h/0.0.0.0:0]) attempting method=keyboard-interactive
```
and then it prints
```
getUserResponses(ClientSessionImpl[u@h/0.0.0.0:0]) no user interaction for name=Password authentication
```

Shouldn`t it be a password method? I set a password like this and even tried to set a preferred auth factory. Do I miss something?
```
clientSession.addPasswordIdentity("pass");
clientSession.setUserAuthFactories(Collections.singletonList(UserAuthPasswordFactory.INSTANCE));
```

**Comment by yaroslavambrozyak** [comment]
I have found a solution for my case
```
SshClient sshClient = SshClient.setUpDefaultClient();
CoreModuleProperties.PREFERRED_AUTHS.set(sshClient, "password");
```
After I set a preferred auth method it started to work. To my understanding, it was using keyboard-interactive and expected some input from a user that was not provided.
