### ISSUE TITLE
After the upgrade to 2.12.0, the query of remote files times out.

### ISSUE THREAD

**Issue by leild** [apache/mina-sshd#488]
### Version

2.12.0

### Bug description

After the upgrade to 2.12.0, the query of remote files times out.
[ ERROR] [2024-04-23 11:47:31.900] [177.209.11.83] [servicecomb-pool-1-thread-1] [com.huawei.csp.om.framework.component.sftp.impl.SftpClientImpl.ls(SftpClientImpl.java:410)] - org.apache.sshd.common.SshException: Timeout expired while waiting for id=109
java.io.UncheckedIOException: org.apache.sshd.common.SshException: Timeout expired while waiting for id=109
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.load(SftpDirEntryIterator.java:181)
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.next(SftpDirEntryIterator.java:120)
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.next(SftpDirEntryIterator.java:45)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.nextEntry(SftpPathIterator.java:111)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.next(SftpPathIterator.java:105)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.next(SftpPathIterator.java:40)

### Actual behavior

java.io.UncheckedIOException: org.apache.sshd.common.SshException: Timeout expired while waiting for id=109
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.load(SftpDirEntryIterator.java:181)
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.next(SftpDirEntryIterator.java:120)
        at org.apache.sshd.sftp.client.impl.SftpDirEntryIterator.next(SftpDirEntryIterator.java:45)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.nextEntry(SftpPathIterator.java:111)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.next(SftpPathIterator.java:105)
        at org.apache.sshd.sftp.client.fs.SftpPathIterator.next(SftpPathIterator.java:40)

### Expected behavior

No timeout. The remote file is found.

**Comment by leild** [comment]
org.apache.sshd.common.SshException: Timeout expired while waiting for id=10

**Comment by tomaswolf** [comment]
Not enough information. Upgrade from what version? Try switching on DEBUG level logging; maybe that gives some clues.
