### ISSUE TITLE
incorrect classloading of SecurityProviders

### ISSUE THREAD

**Issue by jtnord** [apache/mina-sshd#502]
### Version

2.12.1

### Bug description

The mina plugin attempts work out if EdDSA is supported using a different classloader than it actually uses for using `EdDSASecurityProviderUtils` leading to `ClassNotFoundExceptions`

### Actual behavior

`NoClassDefError`

```
Caused by: java.lang.NoClassDefFoundError: net/i2p/crypto/eddsa/spec/EdDSAParameterSpec
	at org.apache.sshd.common.util.security.SecurityUtils.getEDDSAPublicKeyEntryDecoder(SecurityUtils.java:580)
	at org.apache.sshd.common.config.keys.KeyUtils.<clinit>(KeyUtils.java:187)
	at org.apache.sshd.common.config.keys.loader.openssh.OpenSSHRSAPrivateKeyDecoder.<clinit>
```

### Expected behavior

No classloading issues.
the code uses the same classloader to load EdDSA as it uses to see if EdDSA is supported.

### Other information

if you have a non flat classloader (e.g. Jenkins, or any modular app server) then the code has a non reflective way of determining if something is supported or not.

e.g. 

https://github.com/apache/mina-sshd/blob/9ceba3e7ffaeaf79705c2abe3a3cc8aea86fd017/sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityUtils.java#L575-L581

we see a call to `isEDDSACurveSupported` before we attempt to use a staic method from the class `EdDSASecurityProviderUtils` 

However 
https://github.com/apache/mina-sshd/blob/9ceba3e7ffaeaf79705c2abe3a3cc8aea86fd017/sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityUtils.java#L566-L571

looks for the presence of a security provider called "EdDSA" which in no way reflects if the classes are available or not.  

If the "EdDSA" provider was statically registered in the bootclasspath this would work, however it is generally registered by [`EdDSASecurityProviderRegistrar`](https://github.com/apache/mina-sshd/blob/sshd-2.12.1/sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/EdDSASecurityProviderRegistrar.java)

As can be seen here
https://github.com/apache/mina-sshd/blob/9ceba3e7ffaeaf79705c2abe3a3cc8aea86fd017/sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/EdDSASecurityProviderRegistrar.java#L88-L101
this uses `ThreadUtils.resolveDefaultClass` to see if the class is available which adds a the Threads contextClassLoader into the mix to see if the class is there.
If the class is available in the `contextClassloader` but not the current classload, then it would load as the Provider is created (eventually) [here](https://github.com/apache/mina-sshd/blob/sshd-2.12.1/sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityProviderChoice.java#L125-L128) which uses reflection and in the case of this issue the Threads contextClassLoader.

The created provider is then registered in the JVM.

This provider is then used as the gate for "are the EdDSA classes available" for the regular (current) classloader, which in this case they are not which causes a :boom:

whilst it is generally safe to create and Provider dynamically like this, the code that uses the classes from the provider as opposed to the provider itself should take a different approach.
Either they also need to be loaded by reflection (yikes), or the check to see if they are available should not use the provider, but should check the actual class is present in the **current** classloader (ie ignore the context classloader).
Or providers should not be dynamically registered from a context classloader.

**Comment by jtnord** [comment]
(of note BouncyCastle also supports ED25519 curves as does JDK > 15)

**Comment by jansohn** [comment]
seeing something quite similar when re-deploying my web application in Tomcat (without restarting Tomcat):

```
Caused by: java.lang.NoClassDefFoundError: java/security/spec/EdECPublicKeySpec
	at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyFactorySpi.engineGeneratePublic(Unknown Source)
	at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:345)
	at org.apache.sshd.common.util.security.eddsa.bouncycastle.BouncyCastleEdDSASupport.generateEDDSAPublicKey(BouncyCastleEdDSASupport.java:118)
	at org.apache.sshd.common.util.security.eddsa.bouncycastle.BouncyCastleEdDSASupport.generateEDDSAPublicKey(BouncyCastleEdDSASupport.java:51)
	at org.apache.sshd.common.util.security.eddsa.generic.GenericEd25519PublicKeyDecoder.decodePublicKey(GenericEd25519PublicKeyDecoder.java:95)
	at org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser.readPublicKey(OpenSSHKeyPairResourceParser.java:224)
	at org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser.extractKeyPairs(OpenSSHKeyPairResourceParser.java:133)
	at org.apache.sshd.common.config.keys.loader.AbstractKeyPairResourceParser.extractKeyPairs(AbstractKeyPairResourceParser.java:198)
	at org.apache.sshd.common.config.keys.loader.AbstractKeyPairResourceParser.extractKeyPairs(AbstractKeyPairResourceParser.java:167)
	at org.apache.sshd.common.config.keys.loader.AbstractKeyPairResourceParser.loadKeyPairs(AbstractKeyPairResourceParser.java:117)
	at org.apache.sshd.common.config.keys.loader.KeyPairResourceParser$2.loadKeyPairs(KeyPairResourceParser.java:166)
	at org.apache.sshd.common.config.keys.loader.KeyPairResourceLoader.loadKeyPairs(KeyPairResourceLoader.java:157)
	at org.apache.sshd.common.config.keys.loader.KeyPairResourceLoader.loadKeyPairs(KeyPairResourceLoader.java:148)
	at org.apache.sshd.common.config.keys.loader.KeyPairResourceLoader.loadKeyPairs(KeyPairResourceLoader.java:139)
	at org.apache.sshd.common.config.keys.loader.KeyPairResourceLoader.loadKeyPairs(KeyPairResourceLoader.java:130)
	at org.apache.sshd.common.util.security.SecurityUtils.loadKeyPairIdentities(SecurityUtils.java:568)
	at com.updater.jgit.GitRemoteHelper.loadKeyPair(GitRemoteHelper.java:99)
	at com.updater.jgit.GitRemoteHelper.init(GitRemoteHelper.java:74)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 63 more
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.spec.EdECPublicKeySpec]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	... 82 more 
```

Would be great if this could get fixed as the only fix for now is restarting the complete Tomcat instance...

Is there maybe a workaround possible until this gets properly fixed? Like unregistering the BounceCastle provider during undeploy phase of the web application?

**Comment by jansohn** [comment]
My workaround for now which I execute during initialization phase of my web application:

```java
if (Security.getProvider(SecurityUtils.BOUNCY_CASTLE) != null && SecurityUtils.getRegisteredProviders().isEmpty()) {
    log.info("Removing already registered BouncyCastle provider due to classloader issues...");
    Security.removeProvider(SecurityUtils.BOUNCY_CASTLE);
}
```
