### ISSUE TITLE
Getting IOException - "The semaphore timeout period has expired" while using Apache Mina SshClient

### ISSUE THREAD

**Issue by raghamadhu** [apache/mina-sshd#578]
### Version

2.13.1

### Bug description

We are using Apache Mina to connect to an RHEL server, and intermittently we are getting IOException - "The semaphore timeout period has expired" while using Apache Mina SshClient. 

This error only occurs when connecting from a Windows client.

Error only occurs 3 in 10 times. We are trying to execute commands on the remote server using ChannelExec::open method.

### Actual behavior

We are using ClientBuilder to build the client as below
`client = ClientBuilder.builder().hostConfigEntryResolver(hostConfigEntryResolver).serverKeyVerifier(AcceptAllServerKeyVerifier.INSTANCE).forwardingFilter(AcceptAllForwardingFilter.INSTANCE).build();`

Session heartbeat is set to 10 seconds and we are starting the client. 

`client.start();`

Using the session object created, we are opening an ExecChannel, to execute linux commands. 

```
channelExec = session.createExecChannel("<command to execute>")
channelExec.open()
```

This closes the complete session in the client. which interrupts command execution in other channels too. 

### Expected behavior

while a connection is open, and no network disturbances, this should not happen. 

### Relevant log output

```Shell
2024-08-07 13:09:25,424 DEBUG [sshd-SshClient[569b3009]-timer-thread-1] o.a.s.c.i.n.Nio2Session writeBuffer(Nio2Session[local=/0:0:0:0:0:0:0:0:64688, remote=vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) writing 60 bytes
2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.i.n.Nio2Session handleReadCycleFailure(Nio2Session[local=/0:0:0:0:0:0:0:0:64688, remote=vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) IOException after 19180462400 nanos at read cycle=34: The semaphore timeout period has expired.

2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.i.n.Nio2Session exceptionCaught(Nio2Session[local=/0:0:0:0:0:0:0:0:64688, remote=vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) caught IOException[The semaphore timeout period has expired.
] - calling handler
2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientSessionImpl signalAuthFailure(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) type=IOException, signalled=false, first=false: The semaphore timeout period has expired.

2024-08-07 13:09:25,574 WARN [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientSessionImpl exceptionCaught(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22])[state=Opened] IOException: The semaphore timeout period has expired.

java.io.IOException: The semaphore timeout period has expired.

	at sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:309)
	at sun.nio.ch.Iocp.access$700(Iocp.java:46)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:399)
	at java.lang.Thread.run(Thread.java:750)
2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.h.SessionTimeoutListener sessionException(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) IOException: The semaphore timeout period has expired.

2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.h.SessionTimeoutListener sessionClosed(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) un-tracked
2024-08-07 13:09:25,574 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientSessionImpl close(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) Closing immediately
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientSessionImpl signalAuthFailure(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) type=SshException, signalled=false, first=false: Session is being closed
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientConnectionService close(ClientConnectionService[ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]]) Closing immediately
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientConnectionService stopHeartBeat(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) stopping
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientConnectionService stopHeartBeat(ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) stopped
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.ChannelExec close(ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) Closing immediately
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.ChannelExec close(ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) no EOF sent
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.LocalWindow Closing LocalWindow[client](ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22])
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.RemoteWindow Closing RemoteWindow[client](ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22])
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.ChannelExec sendEof(ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) already closing or closed - state=Immediate
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.c.AbstractChannel$GracefulChannelCloseable close(ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22])[immediately=true] processing
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.s.ClientConnectionService unregisterChannel(ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]) result=ChannelExec[id=0, recipient=1]-ClientSessionImpl[installadmin@vmr-iod-1001.ete.ka.sw.ericsson.se/10.223.58.242:22]
2024-08-07 13:09:25,589 DEBUG [sshd-SshClient[569b3009]-nio2-thread-5] o.a.s.c.u.c.SequentialCloseable doClose(org.apache.sshd.common.util.closeable.SequentialCloseable$1@1b3126aa) signal close complete immediately=true
```

### Other information

Local Windows 10 with Apache Mina SSHD 2.13.1
Server - RHEL 9.2 - openssh-8.7p1-30.el9_2.3.x86_64 - openssh-server-8.7p1-30.el9_2.3.x86_64
Java 8 Runtime Environment (for the client)

**Comment by tomaswolf** [comment]
If you search for the exception message "The semaphore timeout period has expired" you'll discover quickly that it is some kind of O/S error message. I don't see what we could do about this.

**Comment by raghamadhu** [comment]
Is this issue related to whatever solved in [Nio2Acceptor]([SSHD-786] Clients can't authenticate after unexpected exception in Nio2Acceptor #40)? I guess, our client uses Nio2Connector. 

Even though it is an O/S level error, the library completely closes all the session channels and exits, which is the concern.

**Comment by tomaswolf** [comment]
As I understand it the exception means the O/S thinks it lost the connection. Hence closing all channels and the session is the right thing to do.

Apparently Windows has some timeout somewhere, and if no message arrives within that time, it produces this error. (At least that is how I read that error messsage.) Evidently this might be a problem for high-latency connections. I don't know if that timeout value can be tweaked at O/S level somehow.

At application level you may perhaps be able to do something by using heartbeats that require the server to reply, and running them in an interval shorter than that timeout (in fact, interval + time until you get the reply < that O/S timeout.) Set properties `CoreModuleProperties.HEARTBEAT_INTERVAL` and `CoreModuleProperties.HEARTBEAT_NO_REPLY_MAX` on the SshClient, the latter > 0. This sends SSH global requests and requests a reply from the server.

If your commands produce output on stdout or stderr, make sure you read it. Otherwise the channel window may drop to zero, and the server won't send data anymore.

**Comment by raghamadhu** [comment]
Thank you so much for the suggestions. We tried to set all these and also improvised our logic to have fresh connections for requests post machine initializations. Almost it is working now. 

However, for the SOCKET_KEEPALIVE requests, we always receive a failure message from Openssh 8.7 server. Any reasons for the same? Do we really need that setting on? Below is the snippet of the failure. 

```
2024-08-14 19:33:22,108 DEBUG [sshd-SshClient[29dcad7e]-timer-thread-1] o.a.s.c.s.ClientSessionImpl encode(ClientSessionImpl[admin@seliicvm08230.bss-te.seli.gic.ericsson.se/214.5.244.124:22]) packet #121 sending command=80[SSH_MSG_GLOBAL_REQUEST] len=31
2024-08-14 19:33:22,108 DEBUG [sshd-SshClient[29dcad7e]-timer-thread-1] o.a.s.c.i.n.Nio2Session writeBuffer(Nio2Session[local=/0:0:0:0:0:0:0:0:61610, remote=seliicvm08230.bss-te.seli.gic.ericsson.se/214.5.244.124:22]) writing 60 bytes
2024-08-14 19:33:22,108 DEBUG [sshd-SshClient[29dcad7e]-nio2-thread-3] o.a.s.c.s.ClientSessionImpl doHandleMessage(ClientSessionImpl[admin@seliicvm08230.bss-te.seli.gic.ericsson.se/214.5.244.124:22]) process #129 SSH_MSG_REQUEST_FAILURE
```

**Comment by tomaswolf** [comment]
> However, for the SOCKET_KEEPALIVE requests, we always receive a failure message from Openssh 8.7 server. Any reasons for the same? Do we really need that setting on?

I don't know. Just leave it at its default setting of `false` then.

**Comment by raghamadhu** [comment]
OK. Thank you so much again for the swift response. We will analyze and remove that.
